package views;

import controllers.DaftarController;
import controllers.UserController;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Daftar;
import utils.ConsDaftarUtil;
import utils.ConstUtil;

public class mainViewMhs extends javax.swing.JFrame {

    Statement st = null;
    Connection con = null;
    
    public mainViewMhs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        bodyPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHomeMhs = new javax.swing.JButton();
        btnHomeReq = new javax.swing.JButton();
        btnHomeView = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblNamaMhs = new javax.swing.JLabel();
        lblRolemhs = new javax.swing.JLabel();
        lblProdiMhs = new javax.swing.JLabel();
        lblKelasMhs = new javax.swing.JLabel();
        lblAsramaMhs = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        newPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtWaktuBerangkat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtWaktukembali = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnRequestIK = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlasan = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        txtTujuan = new javax.swing.JTextField();
        viewPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDaftarReq = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        lblKode = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDaftarApprove = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDaftarDisapprove = new javax.swing.JTable();
        requestPanel = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("VIEW DETAIL");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("VIEW DETAIL");

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Batal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        menuPanel.setBackground(new java.awt.Color(0, 102, 153));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("IZIN KELUAR");
        menuPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 240, 42));

        btnHomeMhs.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnHomeMhs.setText("HOME");
        btnHomeMhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMhsMouseClicked(evt);
            }
        });
        menuPanel.add(btnHomeMhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 220, 40));

        btnHomeReq.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnHomeReq.setText("REQUEST IK");
        btnHomeReq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeReqMouseClicked(evt);
            }
        });
        btnHomeReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeReqActionPerformed(evt);
            }
        });
        menuPanel.add(btnHomeReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 220, 40));

        btnHomeView.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnHomeView.setText("VIEW IK DETAILS");
        btnHomeView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeViewMouseClicked(evt);
            }
        });
        menuPanel.add(btnHomeView, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 220, 50));

        btnLogout.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnLogout.setText("LOG OUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        menuPanel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, 100, 30));

        mainPanel.setBackground(new java.awt.Color(204, 204, 204));
        mainPanel.setLayout(new java.awt.CardLayout());

        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        jLabel2.setText("Selamat datang di MyAziK, ");
        homePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        lblName.setFont(new java.awt.Font("Arial Narrow", 3, 24)); // NOI18N
        lblName.setText("{your name display here}");
        homePanel.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        jLabel13.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel13.setText("Data Profil");
        homePanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        jLabel14.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel14.setText("Nama        :");
        homePanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 189, -1, -1));

        jLabel15.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel15.setText("Role           :");
        homePanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel16.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel16.setText("Prodi         :");
        homePanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel17.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel17.setText("Kelas         :");
        homePanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jLabel18.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel18.setText("Asrama     :");
        homePanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        lblNamaMhs.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblNamaMhs.setText("{name}");
        homePanel.add(lblNamaMhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 189, -1, -1));

        lblRolemhs.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblRolemhs.setText("{role}");
        homePanel.add(lblRolemhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        lblProdiMhs.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblProdiMhs.setText("{prodi}");
        homePanel.add(lblProdiMhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        lblKelasMhs.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblKelasMhs.setText("{kelas}");
        homePanel.add(lblKelasMhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        lblAsramaMhs.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblAsramaMhs.setText("{asrama}");
        homePanel.add(lblAsramaMhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));

        jLabel24.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel24.setText("Username:");
        homePanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        jLabel25.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel25.setText("Password:");
        homePanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 614, -1, -1));

        lblUsername.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblUsername.setText("{Username}");
        homePanel.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, -1, -1));

        lblPassword.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblPassword.setText("{Password}");
        homePanel.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 614, -1, -1));

        mainPanel.add(homePanel, "card2");

        newPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel3.setText("Request Izin Keluar");
        newPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setText("Rencana Berangkat");
        newPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 36));

        txtWaktuBerangkat.setBackground(new java.awt.Color(102, 102, 102));
        txtWaktuBerangkat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtWaktuBerangkat.setForeground(new java.awt.Color(255, 255, 255));
        txtWaktuBerangkat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtWaktuBerangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWaktuBerangkatActionPerformed(evt);
            }
        });
        newPanel.add(txtWaktuBerangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 320, 39));

        jLabel9.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel9.setText("Rencana Kembali");
        newPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, 36));

        txtWaktukembali.setBackground(new java.awt.Color(102, 102, 102));
        txtWaktukembali.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtWaktukembali.setForeground(new java.awt.Color(255, 255, 255));
        txtWaktukembali.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtWaktukembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWaktukembaliActionPerformed(evt);
            }
        });
        newPanel.add(txtWaktukembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 320, 39));

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Keperluan Izin Keluar");
        newPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        btnRequestIK.setBackground(new java.awt.Color(0, 102, 0));
        btnRequestIK.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnRequestIK.setText("Request");
        btnRequestIK.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRequestIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestIKActionPerformed(evt);
            }
        });
        newPanel.add(btnRequestIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 200, 50));

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton3.setText("Batal");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        newPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 200, 50));

        txtAlasan.setColumns(20);
        txtAlasan.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtAlasan.setRows(5);
        jScrollPane2.setViewportView(txtAlasan);

        newPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 710, 120));

        jLabel20.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel20.setText("Tujuan");
        newPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        txtTujuan.setBackground(new java.awt.Color(102, 102, 102));
        txtTujuan.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtTujuan.setForeground(new java.awt.Color(255, 255, 255));
        newPanel.add(txtTujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 720, 50));

        mainPanel.add(newPanel, "card3");

        viewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel6.setText("Riwayat Request IK");
        viewPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        tblDaftarReq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDaftarReq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDaftarReqMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDaftarReq);

        viewPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 770, 110));

        btnDelete.setBackground(new java.awt.Color(255, 51, 0));
        btnDelete.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnDelete.setText("Delete Request");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        viewPanel.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 140, 30));

        lblKode.setText("kode :");
        viewPanel.add(lblKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, -1, -1));

        txtKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeActionPerformed(evt);
            }
        });
        viewPanel.add(txtKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, 30, -1));

        jLabel21.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel21.setText("Daftar request IK");
        viewPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel22.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel22.setText("IK yang telah disetujui");
        viewPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        tblDaftarApprove.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblDaftarApprove);

        viewPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 770, 120));

        jLabel23.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel23.setText("IK yang tidak disetujui");
        viewPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        tblDaftarDisapprove.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblDaftarDisapprove);

        viewPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 770, 130));

        mainPanel.add(viewPanel, "card4");

        jButton4.setBackground(new java.awt.Color(0, 153, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setText("Request Izin Keluar");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel7.setText("Untuk merequest izin keluar, mahasiswa harus memasukkan waktu keluar kampus, waktu kembali ");

        jLabel11.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel11.setText("ke dalam kampus. Kemudian pihak dosen wali dan keasramaan harus mengapprove IK mahasiswa");

        jLabel12.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel12.setText("agar mahasiswa dapat melakukan kegiatan keluar kampus");

        jLabel19.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel19.setText("REQUEST IZIN KELUAR");

        javax.swing.GroupLayout requestPanelLayout = new javax.swing.GroupLayout(requestPanel);
        requestPanel.setLayout(requestPanelLayout);
        requestPanelLayout.setHorizontalGroup(
            requestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(requestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(requestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestPanelLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(261, 261, 261))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestPanelLayout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(295, 295, 295))))
        );
        requestPanelLayout.setVerticalGroup(
            requestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel19)
                .addGap(98, 98, 98)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(66, 66, 66)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(282, 282, 282))
        );

        mainPanel.add(requestPanel, "card5");

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtWaktukembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWaktukembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWaktukembaliActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // add panel
        
        mainPanel.add(requestPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // add panel
        
        mainPanel.add(newPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtWaktuBerangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWaktuBerangkatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWaktuBerangkatActionPerformed

    private void btnHomeMhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMhsMouseClicked
               // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // add panel
        
        mainPanel.add(homePanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnHomeMhsMouseClicked

    private void btnHomeReqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeReqMouseClicked
             // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // add panel
        
        mainPanel.add(requestPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnHomeReqMouseClicked

    private void btnHomeViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeViewMouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // add panel
        
        mainPanel.add(viewPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        tblDaftarReq.removeAll();
        
        DefaultTableModel dtm = new DefaultTableModel();
        tblDaftarReq.setModel(dtm);
        
        dtm.addColumn("kode");
        dtm.addColumn("username");
        dtm.addColumn("rencana berangkat");
        dtm.addColumn("rencana kembali");
        dtm.addColumn("tujuan");
        dtm.addColumn("alasan");
        dtm.addColumn("status dosen");
        dtm.addColumn("Status keasramaan");
        
        DaftarController dc = new DaftarController();
        
        ArrayList<Daftar> daftar = dc.getAllbyUsername();
        
        if(daftar.size() > 0){
            int no = 0;
            for(Daftar d: daftar){
                no++;
                dtm.addRow(new Object[]{
                d.getId(),
                d.getUsername(),
                d.getWaktuPergi(),
                d.getWaktuKembali(),
                d.getTujuan(),
                d.getAlasan(),
                d.getIzinDosen(),
                d.getIzinKeasramaan()
                });
            }
        }
       
        
        tblDaftarApprove.removeAll();
        DefaultTableModel dtma = new DefaultTableModel();
        tblDaftarApprove.setModel(dtma);
        
        dtma.addColumn("kode");
        dtma.addColumn("username");
        dtma.addColumn("rencana berangkat");
        dtma.addColumn("rencana kembali");
        dtma.addColumn("tujuan");
        dtma.addColumn("alasan");
        dtma.addColumn("status dosen");
        dtma.addColumn("Status keasramaan");

        ArrayList<Daftar> daftarApproved = dc.getAllbyApproved();
        
        if(daftarApproved.size() > 0){
            int no = 0;
            for(Daftar d: daftarApproved){
                no++;
                dtma.addRow(new Object[]{
                d.getId(),
                d.getUsername(),
                d.getWaktuPergi(),
                d.getWaktuKembali(),
                d.getTujuan(),
                d.getAlasan(),
                d.getIzinDosen(),
                d.getIzinKeasramaan()
                });
            }
        }
        
        tblDaftarDisapprove.removeAll();
        DefaultTableModel dtmd = new DefaultTableModel();
        tblDaftarDisapprove.setModel(dtmd);
        
        dtmd.addColumn("kode_request");
        dtmd.addColumn("username");
        dtmd.addColumn("rencana berangkat");
        dtmd.addColumn("rencana kembali");
        dtmd.addColumn("tujuan");
        dtmd.addColumn("alasan");
        dtmd.addColumn("status dosen");
        dtmd.addColumn("Status keasramaan");

        ArrayList<Daftar> daftarDisapproved = dc.getAllbyDisapproved();
        
        if(daftarDisapproved.size() > 0){
            int no = 0;
            for(Daftar d: daftarDisapproved){
                no++;
                dtmd.addRow(new Object[]{
                d.getId(),
                d.getUsername(),
                d.getWaktuPergi(),
                d.getWaktuKembali(),
                d.getTujuan(),
                d.getAlasan(),
                d.getIzinDosen(),
                d.getIzinKeasramaan()
                });
            }
        }
       
    }//GEN-LAST:event_btnHomeViewMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.setVisible(false);
        new TampilanAwal().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lblName.setText( ConstUtil.auth.getNama());
        lblRolemhs.setText( ConstUtil.auth.getRole());
        lblNamaMhs.setText( ConstUtil.auth.getNama());
        lblProdiMhs.setText( ConstUtil.auth.getProdi());
        lblKelasMhs.setText( ConstUtil.auth.getKelas());
        lblAsramaMhs.setText( ConstUtil.auth.getAsrama());
        lblUsername.setText(ConstUtil.auth.getUsername());
        lblPassword.setText(ConstUtil.auth.getPassword());
        
        
    }//GEN-LAST:event_formWindowOpened

    private void btnHomeReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeReqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeReqActionPerformed

    private void cekRequest(){
        try{
            if (txtWaktuBerangkat.getText().equals("") || txtWaktukembali.getText().equals("") || txtAlasan.getText().equals("")||txtTujuan.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Data Tidak Boleh Kosong","pesan",JOptionPane.ERROR_MESSAGE);
            }
            
            else{
                st = con.createStatement();
                String simpan = "insert into daftarik (username, waktu_pergi, waktu_kembali, tujuan, alasan) values('"+ConstUtil.auth.getUsername()+"','"+txtWaktuBerangkat.getText()+"','"+txtWaktukembali.getText()+"','"+txtTujuan.getText()+"','"+txtAlasan.getText()+"')";
                st=con.createStatement();
                int SA= st.executeUpdate(simpan);
                JOptionPane.showMessageDialog(this,"Berhasil request");
                }
        }
        
        catch(Exception e){
            mainPanel.removeAll();
            mainPanel.repaint();
            mainPanel.revalidate();

            // add panel

            mainPanel.add(requestPanel);
            mainPanel.repaint();
            mainPanel.revalidate();
        }
    }
    
    DaftarController dc = new DaftarController();
    
    private void btnRequestIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestIKActionPerformed
        String username;
        String waktukeluar;
        String waktukembali;
        String tujuan;
        String alasan;
        
        username = ConstUtil.auth.getUsername();
        waktukeluar = txtWaktuBerangkat.getText();
        waktukembali = txtWaktukembali.getText();
        tujuan = txtTujuan.getText();
        alasan = txtAlasan.getText();

        Daftar daftar = new Daftar(0, username, waktukeluar, waktukembali, tujuan, alasan,"", "");
        cekRequest();
        if(dc.insert(daftar)){
            JOptionPane.showMessageDialog(this,"Berhasil Request","Pesan",JOptionPane.PLAIN_MESSAGE);
            mainPanel.removeAll();
            mainPanel.repaint();
            mainPanel.revalidate();

            mainPanel.add(requestPanel);
            mainPanel.repaint();
            mainPanel.revalidate();
        }
        
    }//GEN-LAST:event_btnRequestIKActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        if (dc.delete(txtKode.getText())) {
            JOptionPane.showMessageDialog(this,"Request berhasil terhapus");
            
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // add panel
        
        mainPanel.add(viewPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        tblDaftarReq.removeAll();
        
        DefaultTableModel dtm = new DefaultTableModel();
        tblDaftarReq.setModel(dtm);
        
        dtm.addColumn("kode");
        dtm.addColumn("username");
        dtm.addColumn("rencana berangkat");
        dtm.addColumn("rencana kembali");
        dtm.addColumn("tujuan");
        dtm.addColumn("alasan");
        dtm.addColumn("status dosen");
        dtm.addColumn("Status keasramaan");
        
        DaftarController dc = new DaftarController();
        
        ArrayList<Daftar> daftar = dc.getAllbyUsername();
        
        if(daftar.size() > 0){
            int no = 0;
            for(Daftar d: daftar){
                no++;
                dtm.addRow(new Object[]{
                
                d.getId(),
                d.getUsername(),
                d.getWaktuPergi(),
                d.getWaktuKembali(),
                d.getTujuan(),
                d.getAlasan(),
                d.getIzinDosen(),
                d.getIzinKeasramaan()
                });
            }
        }
        }
        
        tblDaftarApprove.removeAll();
        DefaultTableModel dtma = new DefaultTableModel();
        tblDaftarApprove.setModel(dtma);
        
        dtma.addColumn("kode");
        dtma.addColumn("username");
        dtma.addColumn("rencana berangkat");
        dtma.addColumn("rencana kembali");
        dtma.addColumn("tujuan");
        dtma.addColumn("alasan");
        dtma.addColumn("status dosen");
        dtma.addColumn("Status keasramaan");

        ArrayList<Daftar> daftarApproved = dc.getAllbyApproved();
        
        if(daftarApproved.size() > 0){
            int no = 0;
            for(Daftar d: daftarApproved){
                no++;
                dtma.addRow(new Object[]{
                d.getId(),
                d.getUsername(),
                d.getWaktuPergi(),
                d.getWaktuKembali(),
                d.getTujuan(),
                d.getAlasan(),
                d.getIzinDosen(),
                d.getIzinKeasramaan()
                });
            }
        }
        
        tblDaftarDisapprove.removeAll();
        DefaultTableModel dtmd = new DefaultTableModel();
        tblDaftarDisapprove.setModel(dtmd);
        
        dtmd.addColumn("kode_request");
        dtmd.addColumn("username");
        dtmd.addColumn("rencana berangkat");
        dtmd.addColumn("rencana kembali");
        dtmd.addColumn("tujuan");
        dtmd.addColumn("alasan");
        dtmd.addColumn("status dosen");
        dtmd.addColumn("Status keasramaan");

        ArrayList<Daftar> daftarDisapproved = dc.getAllbyDisapproved();
        
        if(daftarDisapproved.size() > 0){
            int no = 0;
            for(Daftar d: daftarDisapproved){
                no++;
                dtmd.addRow(new Object[]{
                d.getId(),
                d.getUsername(),
                d.getWaktuPergi(),
                d.getWaktuKembali(),
                d.getTujuan(),
                d.getAlasan(),
                d.getIzinDosen(),
                d.getIzinKeasramaan()
                });
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblDaftarReqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDaftarReqMouseClicked
        // TODO add your handling code here:
        int baris = tblDaftarReq.rowAtPoint(evt.getPoint());
        String kode = tblDaftarReq.getValueAt(baris, 0).toString();
        txtKode.setText(kode);
    }//GEN-LAST:event_tblDaftarReqMouseClicked

    private void txtKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainViewMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainViewMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainViewMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainViewMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainViewMhs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnHomeMhs;
    private javax.swing.JButton btnHomeReq;
    private javax.swing.JButton btnHomeView;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRequestIK;
    private javax.swing.JPanel homePanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAsramaMhs;
    private javax.swing.JLabel lblKelasMhs;
    private javax.swing.JLabel lblKode;
    private javax.swing.JLabel lblNamaMhs;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblProdiMhs;
    private javax.swing.JLabel lblRolemhs;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel newPanel;
    private javax.swing.JPanel requestPanel;
    private javax.swing.JTable tblDaftarApprove;
    private javax.swing.JTable tblDaftarDisapprove;
    private javax.swing.JTable tblDaftarReq;
    private javax.swing.JTextArea txtAlasan;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtTujuan;
    private javax.swing.JTextField txtWaktuBerangkat;
    private javax.swing.JTextField txtWaktukembali;
    private javax.swing.JPanel viewPanel;
    // End of variables declaration//GEN-END:variables
}
