/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.DaftarController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Daftar;
import utils.ConstUtil;

/**
 *
 * @author ASUS
 */
public class mainViewDosen extends javax.swing.JFrame {

    /**
     * Creates new form mainViewDosen
     */
    public mainViewDosen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHomeDosen = new javax.swing.JButton();
        btnViewDosen = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        pnlMain = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblNamaDosen = new javax.swing.JLabel();
        lblRoleDosen = new javax.swing.JLabel();
        lblKelasDosen = new javax.swing.JLabel();
        lblUsernameDosen = new javax.swing.JLabel();
        lblPasswordDosen = new javax.swing.JLabel();
        pnlView = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDaftarReq = new javax.swing.JTable();
        btnDisapprove = new javax.swing.JButton();
        btnApprove = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlMenu.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("IZIN KELUAR");

        btnHomeDosen.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnHomeDosen.setText("HOME");
        btnHomeDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeDosenMouseClicked(evt);
            }
        });

        btnViewDosen.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnViewDosen.setText("VIEW IK");
        btnViewDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewDosenMouseClicked(evt);
            }
        });

        btnLogOut.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnLogOut.setText("LOG OUT");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHomeDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addComponent(btnHomeDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnViewDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pnlMain.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jLabel2.setText("Welcome to MyAzik");

        lblname.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblname.setText("{Name}");

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel4.setText("Data Profil");

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel5.setText("Nama           :");

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel6.setText("Role              :");

        jLabel7.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jLabel7.setText("Wali Kelas  :");

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel8.setText("Username   :");

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel9.setText("Password   :");

        lblNamaDosen.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblNamaDosen.setText("{nama}");

        lblRoleDosen.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblRoleDosen.setText("{role}");

        lblKelasDosen.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblKelasDosen.setText("{asrama}");

        lblUsernameDosen.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblUsernameDosen.setText("{username}");

        lblPasswordDosen.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblPasswordDosen.setText("{password}");

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlHomeLayout.createSequentialGroup()
                        .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(28, 28, 28)
                        .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsernameDosen)
                            .addComponent(lblPasswordDosen)
                            .addComponent(lblKelasDosen)))
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(31, 31, 31)))
                        .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNamaDosen)
                            .addComponent(lblRoleDosen))
                        .addGap(614, 614, 614))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblname)
                .addGap(277, 277, 277))
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblname))
                .addGap(73, 73, 73)
                .addComponent(jLabel4)
                .addGap(155, 155, 155)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblNamaDosen))
                .addGap(26, 26, 26)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblRoleDosen))
                .addGap(31, 31, 31)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblKelasDosen))
                .addGap(18, 18, 18)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblUsernameDosen))
                .addGap(29, 29, 29)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblPasswordDosen))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pnlMain.add(pnlHome, "card2");

        jLabel15.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel15.setText("Daftar Request IK");

        tblDaftarReq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDaftarReq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDaftarReqMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDaftarReq);

        btnDisapprove.setBackground(new java.awt.Color(255, 0, 0));
        btnDisapprove.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnDisapprove.setText("Disapprove");
        btnDisapprove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDisapproveMouseClicked(evt);
            }
        });

        btnApprove.setBackground(new java.awt.Color(51, 255, 51));
        btnApprove.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnApprove.setText("Approve");
        btnApprove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnApproveMouseClicked(evt);
            }
        });

        jLabel3.setText("kode : ");

        javax.swing.GroupLayout pnlViewLayout = new javax.swing.GroupLayout(pnlView);
        pnlView.setLayout(pnlViewLayout);
        pnlViewLayout.setHorizontalGroup(
            pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewLayout.createSequentialGroup()
                .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlViewLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlViewLayout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel15))
                    .addGroup(pnlViewLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(btnDisapprove))
                    .addGroup(pnlViewLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlViewLayout.setVerticalGroup(
            pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisapprove, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        pnlMain.add(pnlView, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        this.setVisible(false);
        new TampilanAwal().setVisible(true);        
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnHomeDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeDosenMouseClicked
      // TODO add your handling code here:
        pnlMain.removeAll();
        pnlMain.repaint();
        pnlMain.revalidate();
        
        // add panel
        
        pnlMain.add(pnlHome);
        pnlMain.repaint();
        pnlMain.revalidate();
    }//GEN-LAST:event_btnHomeDosenMouseClicked

    private void btnViewDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewDosenMouseClicked
// TODO add your handling code here:
        pnlMain.removeAll();
        pnlMain.repaint();
        pnlMain.revalidate();
        
        // add panel
        
        pnlMain.add(pnlView);
        pnlMain.repaint();
        pnlMain.revalidate(); 
        
        tblDaftarReq.removeAll();
        
        DefaultTableModel dtm = new DefaultTableModel();
        tblDaftarReq.setModel(dtm);
        
        dtm.addColumn("kode");
        dtm.addColumn("username");
        dtm.addColumn("rencana berangkat");
        dtm.addColumn("rencana kembali");
        dtm.addColumn("tujuan");
        dtm.addColumn("alasan");
        dtm.addColumn("status dosen");
        dtm.addColumn("Status keasramaan");
        
        DaftarController dc = new DaftarController();
        
        ArrayList<Daftar> daftar = dc.getAllbyKelas();
        
        if(daftar.size() > 0){
            int no = 0;
            for(Daftar d: daftar){
                no++;
                dtm.addRow(new Object[]{
                d.getId(),
                d.getUsername(),
                d.getWaktuPergi(),
                d.getWaktuKembali(),
                d.getTujuan(),
                d.getAlasan(),
                d.getIzinDosen(),
                d.getIzinKeasramaan()
                });
            }
        }
    }//GEN-LAST:event_btnViewDosenMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lblname.setText( ConstUtil.auth.getNama());
        lblRoleDosen.setText( ConstUtil.auth.getRole());
        lblNamaDosen.setText( ConstUtil.auth.getNama());
        lblKelasDosen.setText( ConstUtil.auth.getKelas());
        lblUsernameDosen.setText( ConstUtil.auth.getUsername());
        lblPasswordDosen.setText( ConstUtil.auth.getPassword());
    }//GEN-LAST:event_formWindowOpened

    DaftarController dc = new DaftarController();
    
    private void btnApproveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApproveMouseClicked
        if (dc.updateApprove(txtKode.getText())) {
            JOptionPane.showMessageDialog(this,"Request berhasil diapprove");
            
        pnlMain.removeAll();
        pnlMain.repaint();
        pnlMain.revalidate();
        
        // add panel
        
        pnlMain.add(pnlView);
        pnlMain.repaint();
        pnlMain.revalidate();
        
        tblDaftarReq.removeAll();
        
        DefaultTableModel dtm = new DefaultTableModel();
        tblDaftarReq.setModel(dtm);
        
        dtm.addColumn("kode");
        dtm.addColumn("username");
        dtm.addColumn("rencana berangkat");
        dtm.addColumn("rencana kembali");
        dtm.addColumn("tujuan");
        dtm.addColumn("alasan");
        dtm.addColumn("status dosen");
        dtm.addColumn("Status keasramaan");
        
        DaftarController dc = new DaftarController();
        
        ArrayList<Daftar> daftar = dc.getAllbyKelas();
        
        if(daftar.size() > 0){
            int no = 0;
            for(Daftar d: daftar){
                no++;
                dtm.addRow(new Object[]{
                
                d.getId(),
                d.getUsername(),
                d.getWaktuPergi(),
                d.getWaktuKembali(),
                d.getTujuan(),
                d.getAlasan(),
                d.getIzinDosen(),
                d.getIzinKeasramaan()
                });
            }
        }
        }
    }//GEN-LAST:event_btnApproveMouseClicked

    private void tblDaftarReqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDaftarReqMouseClicked
        // TODO add your handling code here:
        int baris = tblDaftarReq.rowAtPoint(evt.getPoint());
        String kode = tblDaftarReq.getValueAt(baris, 0).toString();
        txtKode.setText(kode);
    }//GEN-LAST:event_tblDaftarReqMouseClicked

    private void btnDisapproveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDisapproveMouseClicked
        // TODO add your handling code here:
        if (dc.updateDisapprove(txtKode.getText())) {
            JOptionPane.showMessageDialog(this,"Request berhasil tidak diapprove");
            
        pnlMain.removeAll();
        pnlMain.repaint();
        pnlMain.revalidate();
        
        // add panel
        
        pnlMain.add(pnlView);
        pnlMain.repaint();
        pnlMain.revalidate();
        
        tblDaftarReq.removeAll();
        
        DefaultTableModel dtm = new DefaultTableModel();
        tblDaftarReq.setModel(dtm);
        
        dtm.addColumn("kode");
        dtm.addColumn("username");
        dtm.addColumn("rencana berangkat");
        dtm.addColumn("rencana kembali");
        dtm.addColumn("tujuan");
        dtm.addColumn("alasan");
        dtm.addColumn("status dosen");
        dtm.addColumn("Status keasramaan");
        
        DaftarController dc = new DaftarController();
        
        ArrayList<Daftar> daftar = dc.getAllbyKelas();
        
        if(daftar.size() > 0){
            int no = 0;
            for(Daftar d: daftar){
                no++;
                dtm.addRow(new Object[]{
                
                d.getId(),
                d.getUsername(),
                d.getWaktuPergi(),
                d.getWaktuKembali(),
                d.getTujuan(),
                d.getAlasan(),
                d.getIzinDosen(),
                d.getIzinKeasramaan()
                });
            }
        }
        }
    }//GEN-LAST:event_btnDisapproveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainViewDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainViewDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainViewDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainViewDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainViewDosen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnDisapprove;
    private javax.swing.JButton btnHomeDosen;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnViewDosen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKelasDosen;
    private javax.swing.JLabel lblNamaDosen;
    private javax.swing.JLabel lblPasswordDosen;
    private javax.swing.JLabel lblRoleDosen;
    private javax.swing.JLabel lblUsernameDosen;
    private javax.swing.JLabel lblname;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlView;
    private javax.swing.JTable tblDaftarReq;
    private javax.swing.JTextField txtKode;
    // End of variables declaration//GEN-END:variables
}
